name: Publish Docker Images

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/slido-quiz-bot:latest .

      # Step 4: Tag the Docker image with GitHub SHA
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/slido-quiz-bot:latest ${{ secrets.DOCKER_USERNAME }}/slido-quiz-bot:${{ github.sha }}

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/slido-quiz-bot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/slido-quiz-bot:${{ github.sha }}
